repos:
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v4.1.1"
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.9.4"
    hooks:
      # Run the linter.
      - id: ruff
        stages: [pre-commit]
      # Run the formatter.
      - id: ruff-format
        stages: [pre-commit]
